### ISSUE TITLE
Webcam not working/not recognised

### ISSUE THREAD

**Issue by ghost** [tlefko/XPS13-9350-Catalina#5]
I remember having webcam in Mojave, but after upgrading to Catalina, Facetime just refuses to acknowledge the webcam. Might be something in IORegister, because the camera is recognised.
It doesn't show up in Hardware->Camera, but rather in Hardware->USB
<img width="587" alt="image" src="https://user-images.githubusercontent.com/53256153/77528502-fe0a1200-6e85-11ea-8691-a5323b1a7fea.png">

The Manufacter field shows something resembling more the serial number of the Camera than the actual manufacturer. Maybe that's something that should be mapped to a different place in IORegistry? 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/53256153/77528974-c2237c80-6e86-11ea-88f3-3abc8c0e97fa.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/53256153/77529022-d0719880-6e86-11ea-83de-b22e6c8f321f.png">

**Comment by tlefko** [comment]
Right so I store the camera here and for me my FaceTime works fine. Anyway to get it recognized this should do the trick. Install the UVC kext in the clover folder to S/L/E then rebuild @manz4rk
 
Honestly that's so strange because I see it's recognized and my FaceTime works and has the same configuration. (By that I mean same setup in the hardware tabs and my camera is recognized. Honestly maybe it might be worth just reinstalling everything. I don't think anyone else has had this bug

**Comment by ghost** [comment]
I'll give it a go, thanks!

Is /S/L/E still a valid path for Catalina? Or should I try /L/E?

**Comment by tlefko** [comment]
@manz4rk just google quickly what is safest to install too

**Comment by ghost** [comment]
Sadly, no luck in either S/L/E or L/E. Additionally, the boot time has increased by around two minutes and the Wi-Fi is not working until 5 minutes into the system...

**Comment by tlefko** [comment]
@manz4rk okay thankfully this issue I can absolutely explain. This happens when you run post install scripts on the build I had these exact issues before. ABSOLUTELY reinstall Catalina with a fresh USB and wipe the orginal partition you installed it too. It will fix the wifi and slow boot time garaunteed. Honestly I strongly believe it'll fix the FaceTime too. I know it's annoying though. To detail the kexts are being loaded twice especially with wifi which to put in terms that are very simple breaks everything and for me the best solution to this was a clean install

**Comment by ghost** [comment]
Funny thing is, just before I started testing your files, I had a nicely working Catalina setup. I have just swapped your CLOVER folder for the one I used just before, and boot time and Wi-Fi issues are gone. Still, "No camera connected" in PhotoBooth.

**Comment by tlefko** [comment]
@manz4rk ohhh so you already had a post script applied right? That would explain why things are so broken actually! If you feel like testing this out the way it's intended you can try making a new partition and booting off a USB. But I'm glad you told me that this wasn't a clean install as the issues you were describing such as the wifi and boot time we're suprising. I strongly believe with clean install the webcam will work / wifi / boot. Just make sure my config is active

**Comment by ghost** [comment]
I think so, I can't remember the post script you're talking about - what does it do? 
Might do a clean install some time, but for now I think I'll tag along with what I have.

**Comment by tlefko** [comment]
@manz4rk they basically install everything into the system. Because the way this build is designed, it causes duplicates and conflicts in kext and patch loading. This fundamentally breaks this build as this is a) why the boot takes so long. B) conflict in wifi patches is why it has the "localized strings" error where wifi slowly turns on where first nothing the turn wifi off is available then it works (which I'm guessing is what you have) c) conflicts in camera patches and duplicate kexts would break the camera which is why it's not working for you. D) this is all because this build is designed with the distinct goal of running as little post install as possible thus everything nearly is patched in on boot from clover, which is why post install stuff generally breaks these

If you want to test this you can just make a small partition and do a sepwrate Catalina install on it just to test this out. But this should explain why you have these bug. Hope it helps!

I'll leave your issue open until you test this, but honestly like I said I think this would solve your problem

**Comment by ghost** [comment]
Ah, that makes sense. Where can I find the post script? I can't find anything in the archive you provided, the README folder inside is empty, and your Readme on the repo doesn't mention the post script anywhere...

**Comment by tlefko** [comment]
@manz4rk sorry I wasn't clear. I think you installed a post from ANOTHER repository. This build of mine intentionally has no post script and having one from another repo would break it. Everything like I said above is done thru clover because in my experience -- post scripts break a lot.

Because post scripts from the other repos modify system files that's why i suggested clean or seperate install to test. I recognized your WiFi bug taking forever to start when I tried Maz's build and after running his post WiFi bug happened and camera

**Comment by ghost** [comment]
Ah OK, I see. That got confusing for a second haha! I will give it a go with your config and report back in couple of hours! Just need to make a Time Machine backup first.

**Comment by tlefko** [comment]
Sounds great!!

**Comment by tlefko** [comment]
@manz4rk update?

**Comment by Saad-LUMS** [comment]
> Honestly that's so strange because I see it's recognized and my FaceTime works and has the same configuration. (By that I mean same setup in the hardware tabs and my camera is recognized. 

Works out of the box for me as well. Detected and works great in FaceTime.

**Comment by ghost** [comment]
@tlefko Had some issues with the install because apparently I downloaded 10.15.4, which was released yesterday. I had to update Clover and kexts to even boot the installer up, but after the install - sadly, still the same thing. Both booting from USB Clover as well as the after copying it to EFI partition. 

Just to add: The camera in the BIOS is enabled, and I just checked on one of Linux liveCD distros using V4L2 Test Bench - the webcam works perfectly there.

**Comment by manz4rk** [comment]
Just to add: The camera in the BIOS is enabled, and I just checked on one of Linux liveCD distros using V4L2 Test Bench - the webcam works perfectly there.

**Comment by ghost** [comment]
Solved: I used this one: 
[UVC2FaceTimeHD.kext.zip](https://github.com/tlefko/XPS13-9350-Catalina/files/4389300/UVC2FaceTimeHD.kext.zip)
